Ens Registration and ENS Resolve Component
heyAuraDev/adex-platform pull request #294
Opened 2020-01-17 13:17 UTC by rori4

- a registration for ens name on identity
- created ens address resolver component with the ENS Front-End Design Guidelines ([https://docs.ens.domains/dapp-developer-guide/front-end-design-guidelines](https://docs.ens.domains/dapp-developer-guide/front-end-design-guidelines))
- css improvements and abstraction in AccountInfo
- lottie file animation on free domain found (suggestion)
- fixes Ability to set an ENS username (closes #197)

related: AdEx: Grow Ethereum: ENS support for every place that an address has to be entered #111
related: ENS (reverse registrar) for displaying addresses #114

2020-01-17 14:11 UTC, Ivshti requested changes

2020-01-17 14:11 UTC, Ivshti commented on src/components/dashboard/account/AccountInfo.js
> +												walletAuthType.replace(/^\w/, chr => {
can this do w/o a regex

2020-01-28 20:21 UTC, Ivshti approved these changes

2020-01-29 07:04 UTC, ivopaunov commented on src/components/common/ens/EnsAddressResolver.js
> +	const useStyles = makeStyles(styles)
This should be outside the func. I'm not sure if this is inside because of the `memo`

2020-01-29 07:04 UTC, ivopaunov commented on src/components/dashboard/forms/web3/SetAccountENSPage.js
> +					<Lottie options={defaultOptions} height={400} width={400}></Lottie>
Remove Lottie until we decide to use it or not.

2020-01-29 07:04 UTC, ivopaunov commented on src/components/dashboard/forms/web3/SetAccountENSPage.js
> +class SetAccountENSPage extends Component {
Is there any reason to use class instead of hooks. I can accept it like that but it will need refactoring - hooks + using validationActions or steps validation as the way it is for login/signup steps.

2020-01-29 07:04 UTC, ivopaunov commented on src/services/smart-contracts/actions/identity.js
> +const publicResolver = '0x226159d592E2b063810a10Ebf6dcbADA94Ed68b8'
Add env.var  for `publicResolver` and `txnsByFeeToken` with `const fees = await getIdentityTxnsTotalFees({ txnsByFeeToken, mainToken })` for `getFeesOnly`. I'll  update the `getIdentityTxnsWithNoncesAndFees` to make sweeps and swap automatically if there is no enough balance in main toke for the fees.

2020-01-29 07:09 UTC, IvoPaunov commented
There are conflicts that needs to be resolved first

2020-01-29 07:38 UTC, rori4 commented on src/components/dashboard/forms/web3/SetAccountENSPage.js
> +class SetAccountENSPage extends Component {
Yes I tried using hooks here but there was some issues with NewTransactionHoc that is being used. With hooks it did not work properly for some reason that i couldn't figure out.

2020-01-29 07:39 UTC, rori4 commented on src/components/dashboard/forms/web3/SetAccountENSPage.js
> +					<Lottie options={defaultOptions} height={400} width={400}></Lottie>
ok

2020-01-29 07:42 UTC, rori4 commented on src/components/common/ens/EnsAddressResolver.js
> +	const useStyles = makeStyles(styles)
Why should this be outside of the function? React hooks won't work if they are outside

2020-01-29 07:43 UTC, rori4 commented on src/components/common/ens/EnsAddressResolver.js
> +	const useStyles = makeStyles(styles)
Do you mean the ```const useStyles = makeStyles(styles)``` only?

2020-01-29 08:02 UTC, IvoPaunov commented on src/components/common/ens/EnsAddressResolver.js
> +	const useStyles = makeStyles(styles)
yes just `const useStyles = makeStyles(styles)`

2020-01-29 08:04 UTC, IvoPaunov commented on src/components/dashboard/forms/web3/SetAccountENSPage.js
> +class SetAccountENSPage extends Component {
Ok, leave it like that.

2020-01-29 09:54 UTC, ivopaunov approved these changes

2020-01-29 09:54 UTC, merged