Getting Started Guide With Tutorials & Translation Update
heyAuraDev/adex-platform pull request #365
Opened 2020-02-27 16:38 UTC by rori4

- UX: getting started guide #79 (This adds all the steps except the bonus one which is blocked from the relayer)
- added components mapping to translations. Not you can add components tot t('TRANSLATE", {components: [<Comp1/>, <Comp2/>]}). Currently nesting components is not supported
- added all the tutorials as well

2020-02-27 16:41 UTC, rori4 commented on src/components/confirm/Confirm.js
> -					<DialogContentText id='alert-dialog-description'>
This is commented out because with the translation with components it gives errors as this is a `<p>` tag

2020-02-27 16:47 UTC, rori4 commented on src/components/dashboard/charts/simplified.js
> +						callback: function(tick, index, array) {
This fixes the last data points that are missing 
![missing datapoint](https://user-images.githubusercontent.com/22402693/75465622-8ed9f480-5991-11ea-811f-e74fe791cd9c.png)

2020-03-02 13:02 UTC, ivopaunov requested changes

2020-03-02 13:02 UTC, ivopaunov commented on src/components/common/anchor/anchor.js
> +export const ExternalAnchor = ({ href, children, style }) => (
The main reason for this component to exist is because of the external links.
When you make "ExternalAnchor" be sure there is attribute ```rel='noopener noreferrer'```

2020-03-02 13:02 UTC, ivopaunov commented on src/selectors/accountSelectors.js
> +	({ withBalance }) => withBalance || {}
It doesn't work any more use `selectChannelsWithUserBalancesEligible`

2020-03-02 13:02 UTC, ivopaunov commented on src/services/translations/translations.js
> +const addComponents = (tpl, components) => {
Don't not do this. If you want component in the translations, add the components in the translations strings and sanitize them here.
I can help with that if you want.

2020-03-02 13:02 UTC, ivopaunov commented on src/components/confirm/Confirm.js
> -					<DialogContentText id='alert-dialog-description'>
see the comment for adding components to translations

2020-03-02 13:02 UTC, ivopaunov commented on src/components/dashboard/dashboard/Dashboard.js
> +			setDataLoaded(true)
I'm not sure but maybe you need to `await` campaigns loop as well.

2020-03-02 20:27 UTC, merged